import awkward as ak


def remove_class_tokens(generated_output, n_classes):
    """Removes class token, and subtract the number of classes to shift the non-start tokens back
    to the form that the de-tokenizer expects.

    Parameters
    ----------
    generated_output: ak.Array
        The output generated by the model.
    n_classes: int
        Number of classes that were used in class_token_dict.

    Returns
    ----------
    ak.Array
    """

    output = ak.concatenate(
        [generated_output[:, :1], (generated_output[:, 2:] - n_classes)], axis=1
    )
    return output
